"""Write batch 2 (rows 14-25, R013-R024) reviewer fields. Only touches columns I-AA."""

import datetime
import sys

import openpyxl

PATH = "01_round1_blinded_review.xlsx"
TODAY = datetime.date.today().isoformat()

ROWS = {
    14: [
        "COMPLETE",
        "PARTIAL",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "UNCLEAR",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "至少一个对准协同工作空间的成像装置，以单独跟踪协同工作空间内人体构件的位置；其中所述控制器被配置为基于执行所述至少一个人工执行的操作的身体构件的单独跟踪位置来引导执行所述至少一个机器人操作的所述至少一个机器人的运动",
        "成像装置单独跟踪人体构件位置→控制器据此引导机器人运动，属接近监测型 HRI 机制（IN_SCOPE）。但文本未出现安全用语，跟踪目的在于支持同时人机作业而非明言防护，安全相关性判 PARTIAL；无明确保护动作（减速/停止等），response=NO；危险阻断作用未明言，barrier=UNCLEAR。",
        "MEDIUM",
        6,
        TODAY,
    ],
    15: [
        "COMPLETE",
        "INCIDENTAL",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "所述工业机器人(8)具有多个机器人轴(I-VII)，所述机器人轴中的每一个具有传感器，所述传感器用于检测路径和/或位置并且用于吸收外部作用的负载，特别是力或力矩",
        '触觉工业机器人用于方向盘测量（对中、测转角/滞后），力/力矩传感服务于测量精度而非安全（对照手册边界示例"检测外力用于提高轨迹精度"），INCIDENTAL+OFF_TOPIC。有负载传感与力控轴故 sensor/decision=YES，无保护响应。',
        "HIGH",
        5,
        TODAY,
    ],
    16: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "YES",
        "SLOW",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "监控所述机器人(11)的区域(15)，并且检测干扰，所述干扰从在所述区域(15)中或在所述区域(15)中的物体(13)穿入，使得所述机器人(11)危及相应的物体(13)……根据为各个区段确定的频率(k)……确定修改的速度曲线",
        'HRC 中监控机器人区域、检测穿入干扰（机器人危及物体）→按区段统计干扰频率→修改速度曲线供后续控制，危险降低是主要技术功能（DIRECT），保护动作=降速（SLOW）。文本说"物体"未明言人体伤害，harm=INDIRECT。',
        "MEDIUM",
        5,
        TODAY,
    ],
    17: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "NONE",
        "OTHER",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "确定所述任务步骤列表中的每个任务步骤对应于由所述传感器捕获的所述场景中的人类的行为的概率；基于所述概率确定预测的下一意图步骤",
        "意图跟踪（与材料包中另一条记录 claim 文本相同，属同族重复）：视觉捕获场景、预测人类下一意图步骤并执行操作，手册明确将意图跟踪列为 OFF_TOPIC，无安全用语。检测人的行为 sensor=YES（视觉故 sensing=OTHER），意图/概率判断 decision=YES，无保护响应。",
        "HIGH",
        3,
        TODAY,
    ],
    18: [
        "COMPLETE",
        "INCIDENTAL",
        "INDIRECT",
        "UNCLEAR",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "UNCLEAR",
        "ABSENT",
        "IN_SCOPE",
        "MULTIPLE",
        "基于所检测的力和转矩以及机械手建模的期望力来配置机器人系统，并且控制目标转矩",
        "力/力矩传感+建模目标力矩的偏差型控制，摘要称适用于 HRC，但权利要求未说明安全用途（碰撞检测/保护），安全相关性 INCIDENTAL；接触语境（对象是人还是物体）文本不明，contact=UNCLEAR；防护阻断作用未明言，barrier=UNCLEAR。力感知为本，主要依赖间接线索，信心 LOW。",
        "LOW",
        6,
        TODAY,
    ],
    19: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "NONE",
        "NO",
        "NO",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "输送装置形成为重力输送机和向下倾斜输送机，其上安装有工业机器人，被设置成可通过其自身的重量移动",
        "工业机器人安装在重力输送轨道上靠自重移动，纯机械/物流布置，无任何安全机制、传感或判断环节。",
        "HIGH",
        3,
        TODAY,
    ],
    20: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PHYSICAL_HRI",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "OTHER",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "一个或多个具有集成的动力控制或力控制的机器人轴(I-VII)，相应的机器人轴负载作用(I-VII)检测传感器(11)，并且附加地在管芯加工区域(3)人身保护装置(4)被布置，包括致动器(5)具有激活和去激活",
        "HRC 工业机器人：力控轴集成负载检测（sensor=YES，力控含控制条件 decision=YES），加工区附加可激活/去激活的人身保护装置——人身保护明确（harm=DIRECT）。保护装置具体动作类型未说明，记 OTHER。与材料包中另一条记录同族（附加致动器激活特征）。",
        "MEDIUM",
        5,
        TODAY,
    ],
    21: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "NONE",
        "NO",
        "NO",
        "YES",
        "WARNING",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "said safety system setting for using from the track for the position and timing information for signal transmission to the human-robot cooperation environment, and wherein, said safe system so as to comprise of vision and/or hearing of single delivery information for the device",
        "与机器人配合使用的安全系统：将规划轨迹的位置/时序信息以视觉/听觉信号传递给 HRC 环境，属警告型保护（WARNING, response=YES）。信息来自控制器规划轨迹而非传感检测，sensor=NO、decision=NO。面向 HRC 安全警示，IN_SCOPE。claim 为翻译质量较差的实用新型文本，信心 MEDIUM。",
        "MEDIUM",
        5,
        TODAY,
    ],
    22: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "NONE",
        "NO",
        "NO",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "提供具有至少两个铰接臂(21、22)的机器人(2)，其中，在每个铰接臂上布置具有螺钉工具的螺钉单元……将所述螺旋叶片插入所述接收装置中以形成形状配合的连接，以及借助于所述机械手操纵所述组件",
        "双臂机器人用螺钉单元操纵组件的装配方法，面向工件，无安全机制、传感、判断或保护环节。",
        "HIGH",
        3,
        TODAY,
    ],
    23: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "UNCLEAR",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "在支撑台上设置传感器，传感器是一种人协作机器人系统，其特征在于检测人侵入了机器人的工作范围",
        "权利要求区别特征为传感器检测人侵入机器人工作范围，安全检测是发明点（DIRECT）；侵入判定属状态判断 decision=YES。所提供的 claim/摘要文本止于检测环节，未含保护动作文字，response=NO；仅靠检测的阻断作用未明言，barrier=UNCLEAR。",
        "MEDIUM",
        5,
        TODAY,
    ],
    24: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "COLLISION_CONTACT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "RETREAT",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "由上述外力检测部检测出的外力大于第一阈值时，指示上述外力向缩小的方向移动的躲避动作的躲避动作指令部(22)……当从躲避区域脱离时停止躲避操作的躲避操作停止部(24)",
        "人机共享作业空间：外力检测→超第一阈值→指示沿减小外力方向躲避（RETREAT），并设躲避区域与停止部防止误检测导致的过度退避。完整机制链；外力涉人共享空间但未明言伤害，harm=INDIRECT。",
        "HIGH",
        5,
        TODAY,
    ],
    25: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PHYSICAL_HRI",
        "PROXIMITY",
        "YES",
        "YES",
        "YES",
        "SLOW",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "基于所述用户的拍摄信息来评价安全度的安全度生成部，其根据该安全度来生成包含预设所述用户与其周围的所述操作动作主体的相互作用的区域的某个区域……规定所述操作动作主体在这些区域中的各操作动作速度的动作指示部",
        '明确以"安全且灵活的人-机器人接触"为目的（摘要）：拍摄信息计算用户位置/姿势→按安全度生成用户周围区域→分区规定动作速度（SLOW）。与用户接触明确（harm=DIRECT），完整机制链，IN_SCOPE。',
        "HIGH",
        5,
        TODAY,
    ],
}

wb = openpyxl.load_workbook(PATH)
ws = wb["01_REVIEW"]
for r, vals in ROWS.items():
    for i, v in enumerate(vals):
        ws.cell(row=r, column=9 + i, value=v)
try:
    wb.save(PATH)
except PermissionError:
    print("LOCKED: file still open in Excel, nothing saved")
    sys.exit(2)
print("SAVED rows 14-25, date =", TODAY)
