"""Write batch 6 (rows 62-73, R061-R072) reviewer fields. Only touches columns I-AA."""

import datetime
import sys

import openpyxl

PATH = "01_round1_blinded_review.xlsx"
TODAY = datetime.date.today().isoformat()

# Each value list: coding values and an evidence-source tag, then two free-text
# fields: (1) a verbatim claim/abstract excerpt quoted from the source patent
# record, kept in the original language exactly as exported for traceability, and
# (2) the reviewer's rationale note in Chinese, with an English gloss in the
# "# EN:" comment line directly beneath it. The trailing fields are confidence,
# coding time (minutes), and coding date.
ROWS = {
    62: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PHYSICAL_HRI",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "在所述接触力超过规定的阈值的情况下，设置使所述机器人向使所述机器人停止或减小所述接触力的方向退避的接触力监视部",
        '带直接示教(lead-through)的人协作工业机器人：接触力检测→超阈值→停止或向减小接触力方向退避（MULTIPLE=STOP+RETREAT）；示教开关激活时解除监视。摘要明确"确保操作者安全"，harm=DIRECT。完整机制链。',
        # EN: Industrial robot for human collaboration with direct (lead-through) teaching: contact-force detection -> threshold exceeded -> stop or retreat in the direction that reduces the contact force (MULTIPLE=STOP+RETREAT); monitoring is released while the teaching switch is active. The abstract explicitly states 'ensuring operator safety', so harm=DIRECT. Complete mechanism chain.
        "HIGH",
        5,
        TODAY,
    ],
    63: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "COLLISION_CONTACT",
        "PROXIMITY",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "其中在评估模块(38)中，关于人的损伤的经验确定的数据被存储在具有特定边界几何形状的固体与人的特定身体部分发生的碰撞中……从评估模块(38)输出速度，该速度被接受为机械手(10)的参考点的允许处理速度(V_ZUL)",
        '与材料包中 R012 同族的规划方法：记录布局/MRK 区域/极限几何与质量/运动计划→评估模块基于"固体与人身体部位碰撞致人损伤的经验数据"确定允许处理速度，并将碰撞风险身体部位分配给 MRK 区域。碰撞致伤数据明确（harm=DIRECT）。方法止于速度规划，无运行期保护动作（response=NO）。',
        # EN: Planning method from the same family as R012 in the source pack: record the layout / MRK (human-robot collaboration) zones / limiting geometry and masses / motion plan -> the evaluation module determines the permissible processing speed based on 'empirical data on injuries to specific human body parts from collisions with solids of specific boundary geometry' and assigns at-risk body parts to the MRK zones. Collision-injury data is explicit (harm=DIRECT). The method stops at speed planning, with no runtime protective action (response=NO).
        "MEDIUM",
        6,
        TODAY,
    ],
    64: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "COLLISION_CONTACT",
        "BOTH",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "基于来自力或扭矩的传感元件的读数，计算可移动部件的动态模型，以生成至少施加在工具端部上的估计外力，响应于所估计的外力超过设定极限而停止所述可移动部件……响应于所述测量距离下降到所述距离阈值以下，将速度监测点减慢到设定速度",
        "与材料包中 R053 同族加强版：接近传感（距阈值→减速/停止）+关节测速（超速→停止）+力/力矩传感元件经动态模型估计外力（超限→停止），双通道 sensing=BOTH，action=MULTIPLE(SLOW+STOP)。完整机制链，物体未限定人，harm=INDIRECT。",
        # EN: Enhanced version from the same family as R053 in the source pack: proximity sensing (distance below threshold -> slow/stop) + joint speed measurement (overspeed -> stop) + force/torque sensing elements estimating external force via a dynamic model (limit exceeded -> stop); dual-channel, sensing=BOTH, action=MULTIPLE(SLOW+STOP). Complete mechanism chain; the object is not restricted to humans, so harm=INDIRECT.
        "HIGH",
        5,
        TODAY,
    ],
    65: [
        "COMPLETE",
        "INCIDENTAL",
        "INDIRECT",
        "COLLISION_CONTACT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "the force detection value is calculated by subtracting a corrected value from the measurement value, and a correction value updating unit…when the robot is stopped or operates at a constant speed and the…force detecting change amplitude value below the threshold value",
        "人机交互机器人系统：力传感器测量值减校正值以提高小接触力检测精度，校正更新条件含波动阈值判断（decision=YES）。权利要求核心是测量/校正技术而非安全防护（INCIDENTAL），无保护动作（response=NO, barrier=NO）。力感知为主要内容，IN_SCOPE。",
        # EN: Human-robot interaction robot system: a corrected value is subtracted from the force-sensor measurement to improve detection accuracy for small contact forces; the correction-update condition includes a fluctuation-threshold judgment (decision=YES). The core of the claim is measurement/correction technique rather than safety protection (INCIDENTAL), with no protective action (response=NO, barrier=NO). Force sensing is the main content, so IN_SCOPE.
        "MEDIUM",
        5,
        TODAY,
    ],
    66: [
        "COMPLETE",
        "PARTIAL",
        "INDIRECT",
        "OBJECT_ENVIRONMENT",
        "PROXIMITY",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "UNCLEAR",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "其中，工作装置与工业机器人相关的检测器(7)用于检测未预料到的工件的运动(5)",
        "HRC 触觉工业机器人+可动工件：检测装置检测工件的意外运动。防护用途（防工件滑脱伤人）文本未明言，安全相关性 PARTIAL、harm=INDIRECT；claim 止于检测，response=NO，barrier=UNCLEAR。译文残缺，信心 MEDIUM。",
        # EN: HRC haptic industrial robot with a movable workpiece: a detection device detects unexpected workpiece motion. A protective purpose (preventing injury from a slipping workpiece) is not stated in the text, so safety relevance is PARTIAL and harm=INDIRECT; the claim stops at detection, so response=NO and barrier=UNCLEAR. The translation is fragmentary; confidence MEDIUM.
        "MEDIUM",
        5,
        TODAY,
    ],
    67: [
        "COMPLETE",
        "PARTIAL",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "获得场景中的被占用空间的体素化表示……使用拓扑映射在场景中的感兴趣点周围形成未被占用空间的分层凸多胞形(HCP)区域；以及确定机器人从所述HCP区域内的所述兴趣点到终点的路径",
        "HRC 中基于深度相机体素化占用空间→构建无占用分层凸多胞形自由空间→规划无碰撞路径。主功能为运动规划，无碰撞属安全组成（PARTIAL）；claim 止于路径确定，无运行期保护动作（response=NO）；无碰撞规划本身限制危险发展，barrier=YES。",
        # EN: In HRC, voxelized occupied space from a depth camera -> construction of unoccupied hierarchical convex polytope (HCP) free space -> collision-free path planning. The main function is motion planning; collision-freeness is a safety component (PARTIAL); the claim stops at path determination, with no runtime protective action (response=NO); collision-free planning itself limits hazard development, so barrier=YES.
        "MEDIUM",
        5,
        TODAY,
    ],
    68: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "NONE",
        "NO",
        "YES",
        "YES",
        "OTHER",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "基于所述协作策略来确定新的协作位置……基于所述协作区域内的所述预定协作位置的随机分布来选择所述新的协作位置；将所述移动方案的协作位置更新为所述新的协作位置",
        "机器人安全系统（摘要明示 improving the safety of HRC）：按随机化策略在协作区域内随机选取新协作位置并更新移动计划，降低可预测重复运动带来的情境风险。运动随机化属保护性措施（OTHER），无传感检测（sensor=NO），策略选择属判断（decision=YES）。",
        # EN: Robot safety system (the abstract explicitly states 'improving the safety of HRC'): a randomization strategy randomly selects new collaboration positions within the collaboration area and updates the movement plan, reducing the situational risk of predictable repetitive motion. Motion randomization is a protective measure (OTHER); there is no sensing (sensor=NO); strategy selection is a judgment (decision=YES).
        "MEDIUM",
        5,
        TODAY,
    ],
    69: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "NONE",
        "NO",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "PLAUSIBLE_ONLY",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "判定部，判定针对所述对象物的工作种类；控制部，其控制安装与由所述判定部判定的作业种类对应的所述工具的动作，并控制与所述作业种类对应的动作",
        "与材料包中 R006/R049 同族：按作业种类判定→控制工具安装与作业，无安全机制（OFF_TOPIC）。判定部→控制部为正常控制流，按校准口径 PLAUSIBLE_ONLY。",
        # EN: Same family as R006/R049 in the source pack: work-type determination -> control of tool mounting and the work; no safety mechanism (OFF_TOPIC). The determination unit -> control unit flow is a normal control flow; PLAUSIBLE_ONLY per the calibration convention.
        "HIGH",
        3,
        TODAY,
    ],
    70: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "COLLISION_CONTACT",
        "BOTH",
        "YES",
        "YES",
        "YES",
        "OTHER",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "用于检测工业机器人(2)或加工工具(3)带有障碍物(7)，特别是一种工作人员……另外工业机器人(2)之间的距离(d)和/或加工工具(3)和障碍物(7)检测……实施至少一个对障碍物的支撑件(A)",
        "HRC 工作装置：检测装置检测机器人/工具与工作人员已发生的碰撞+检测与障碍物距离（sensing=BOTH）→按碰撞/距离实施至少一项保护措施（类型因译文截断未明，记 OTHER）。明确与工作人员碰撞，harm=DIRECT。",
        # EN: HRC work apparatus: a detection device detects collisions that have already occurred between the robot/tool and a worker + detects the distance to obstacles (sensing=BOTH) -> at least one protective measure is applied based on collision/distance (type unclear because the translation is truncated; coded OTHER). Collision with a worker is explicit, so harm=DIRECT.
        "MEDIUM",
        5,
        TODAY,
    ],
    71: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PROXIMITY_SEPARATION",
        "UNCLEAR",
        "YES",
        "YES",
        "YES",
        "WARNING",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "MIXED",
        "FIRST_CLAIM",
        "其中传感器系统(101)检测机器人(100)和人(99)之间的危险情况；以及反馈步骤，响应于检测到所述危险情况，向与所述人(99)相关联的穿戴式增强现实(AR)装置(103)发送控制信号……呈现与所述危险情况有关的反馈信息",
        "传感器系统检测机器人与人之间的危险情况→向人员的可穿戴 AR 设备发送反馈呈现危险信息（WARNING）。危险检测明确（harm=DIRECT），但传感类型未说明（sensing=UNCLEAR）。主内容为 AR 反馈通道+危险警告安全机制，按手册（AR 列 OFF_TOPIC）折中 MIXED。",
        # EN: A sensor system detects dangerous situations between the robot and a person -> feedback is sent to the person's wearable AR device to present hazard information (WARNING). Hazard detection is explicit (harm=DIRECT), but the sensing type is not specified (sensing=UNCLEAR). The main content is an AR feedback channel plus a hazard-warning safety mechanism; per the codebook (AR is listed as OFF_TOPIC) this is a compromise, coded MIXED.
        "MEDIUM",
        5,
        TODAY,
    ],
    72: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "YES",
        "OTHER",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "检测单元，用于检测所述工人的位置和/或所述工人运动模式……至少一个监测传感器，用于确定和监测机器人周围的至少一个危险区域……用于检测工作人员和/或跨越区域和/或危险机器人中的至少一个；以及控制器……控制机器人……响应于检测到的位置",
        "HRC 监视系统：检测工人位置/运动模式+监测机器人周围危险区域→允许/不允许位置判定与越界检测→控制器响应控制机器人（保护动作类型译文未明，记 OTHER）。危险区域越界明确，harm=DIRECT。",
        # EN: HRC monitoring system: detection of worker position/motion patterns + monitoring of danger zones around the robot -> permitted/not-permitted position judgments and boundary-crossing detection -> the controller responds by controlling the robot (protective-action type unclear in the translation; coded OTHER). Crossing into a danger zone is explicit, so harm=DIRECT.
        "MEDIUM",
        5,
        TODAY,
    ],
    73: [
        "COMPLETE",
        "PARTIAL",
        "INDIRECT",
        "OBJECT_ENVIRONMENT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "LIMIT_FORCE",
        "GENERAL_ROBOT",
        "UNCLEAR",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "在依据所述导纳力控模式控制每个机械臂末端在沿所述负载接触面的法线方向上的实际接触力达到期望作用力的情况下，检测是否存在外界施加于任意机械臂末端和/或所述负载上的外力；若存在外力，则根据……外力分量……计算对应方向上的位置偏移量……控制所述对应机械臂进行运动以响应负载跟随操作",
        "多机械臂人机协作控制：导纳力控将负载接触面法向接触力调节至期望值（LIMIT_FORCE），并检测外力按各方向控制模式计算位置偏移实现负载跟随。主功能为协同搬运的力控，安全为重要组成（PARTIAL）；接触对象为负载，contact=OBJECT_ENVIRONMENT；防护阻断作用未明言，barrier=UNCLEAR。",
        # EN: Multi-arm human-robot collaborative control: admittance force control regulates the contact force normal to the load contact surface to a desired value (LIMIT_FORCE), and detected external forces are used to compute position offsets per directional control modes to achieve load following. The main function is force control for cooperative carrying; safety is an important component (PARTIAL); the contact object is the load, so contact=OBJECT_ENVIRONMENT; a protective blocking role is not stated, so barrier=UNCLEAR.
        "MEDIUM",
        6,
        TODAY,
    ],
}

wb = openpyxl.load_workbook(PATH)
ws = wb["01_REVIEW"]
for r, vals in ROWS.items():
    for i, v in enumerate(vals):
        ws.cell(row=r, column=9 + i, value=v)
try:
    wb.save(PATH)
except PermissionError:
    print("LOCKED: file still open in Excel, nothing saved")
    sys.exit(2)
print("SAVED rows 62-73, date =", TODAY)
