"""Write batch 3 (rows 26-37, R025-R036) reviewer fields. Only touches columns I-AA."""

import datetime
import sys

import openpyxl

PATH = "01_round1_blinded_review.xlsx"
TODAY = datetime.date.today().isoformat()

ROWS = {
    26: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "YES",
        "RETREAT",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "而当人体处于接近区域时，接近传感器的输出变高，使机器人控制器开始向后移动机器人机械手，避免碰撞",
        "工业机器人安全带：三个红外接近传感器按距离分区检测人体→微控制器按区域判定→人进入接近区域时机械手向后移动避免碰撞（RETREAT），完整机制链，明确避免碰撞（harm=DIRECT）。",
        "HIGH",
        4,
        TODAY,
    ],
    27: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "COLLISION_CONTACT",
        "BOTH",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "MULTIPLE",
        "当所述传感器数据指示超过阈值力的外力时，停止所述可移动部件中的所述至少一个的运动，以及响应于所测量的速度超过速度限制，停止所述可移动部件中的所述至少一个的运动；Abstract: haptic warning and proximity sensing",
        "与材料包中 R008 同族（壳体元件）：力阈值停止+超速停止（claim），摘要明确触觉振动告警与接近感知，故 sensing=BOTH、action=MULTIPLE(STOP+WARNING)。完整机制链，人体伤害路径合理但未明言，harm=INDIRECT。",
        "HIGH",
        4,
        TODAY,
    ],
    28: [
        "COMPLETE",
        "PARTIAL",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "UNCLEAR",
        "ABSENT",
        "IN_SCOPE",
        "MULTIPLE",
        "用于测量一个或多个物体或身体部分(12)的距离(17)……并且在距离信息(17)的组合的基础上，机器人系统(2)可以通过在控制系统(9)中的评估，具体地线性地或根据任何期望的特性曲线来移动和引导",
        'MRK 中非接触式引导：多个距离传感器测量身体部位距离→控制系统评估信号→引导机器人运动。摘要称目标是"secure and effective"协作，但主功能是非接触引导（便利交互），安全为重要但非唯一组成，PARTIAL。无减速/停止等保护动作文字，response=NO；危险阻断作用未明言，barrier=UNCLEAR。',
        "MEDIUM",
        6,
        TODAY,
    ],
    29: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "COLLISION_CONTACT",
        "FORCE_TORQUE",
        "YES",
        "NO",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "具有弹性突起(12)和用于防止事故的机器人传感器系统；Title/Abstract: A robot sensor for human-robot collision…promote safety of a worker",
        '人-机器人碰撞传感器：弹性导体+凹槽+弹性突起的接触式传感结构，明确"防止事故"、提升工人安全（harm=DIRECT）。权利要求仅描述传感器机械结构，无阈值/判断与保护响应环节，decision=NO、response=NO。检测目的明确为事故防护，barrier=YES。',
        "MEDIUM",
        5,
        TODAY,
    ],
    30: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "COLLISION_CONTACT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "RETREAT",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "MULTIPLE",
        "多个触觉传感器，其设置在所述机器人主体上以检测接触……基于所述触觉数据确定安全动作；以及响应于检测到的接触，控制机器人本体执行安全动作；Abstract: The safety action may comprise retracting the robot body away from a detected contact point.",
        "与材料包中 R004 同族（安全 HRI 触觉传感系统）：触觉传感检测接触→确定安全动作→执行安全动作，摘要示例为远离接触点回缩（RETREAT）且可按接触力调节动作幅度。完整机制链，明确以安全 HRI 为目的。",
        "HIGH",
        3,
        TODAY,
    ],
    31: [
        "COMPLETE",
        "PARTIAL",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "YES",
        "SLOW",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "MIXED",
        "FIRST_CLAIM",
        "从感测数据生成人类安全区(504)并维持与机器人臂工作空间相关联的机器人安全区(502)，确定人类安全区(504)和机器人安全区(502)之间的空间重叠(508)的程度，并基于所确定的空间重叠来调节机器人臂运动轨迹的执行速度",
        '成像感知人手位置/接近度→人/机安全区→按空间重叠程度调节执行速度（SLOW），安全机制明确；但权利要求同等核心是神经网络按"协作生产率得分"排序轨迹（非安全主功能），故 PARTIAL+MIXED。人体伤害路径合理但未明言，harm=INDIRECT。',
        "HIGH",
        6,
        TODAY,
    ],
    32: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "NONE",
        "NO",
        "NO",
        "NO",
        "NONE",
        "NON_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "A fixing device for semiconductor grinding processing, comprising a machine body (1), wherein the top surface of the machine body (1) is provided with a groove (2)…rotating wheels (3)…conveyor belt (6)",
        "半导体研磨加工固定装置（转轮+传送带夹持基板），纯机械工装，主要对象不是机器人系统（NON_ROBOT），无任何安全机制。",
        "HIGH",
        3,
        TODAY,
    ],
    33: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "NONE",
        "NONE",
        "NO",
        "YES",
        "NO",
        "NONE",
        "NON_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "用于确定用于与系统协作的人-机器人的安全限值，并且被配置为基于……第一和第二参数(V，M，A，K)与预定值……之间的机械固定关系……输出……极限值(V111，V124，V224)",
        "确定 HRC 系统安全限值的便携式手持装置：基于参数间固定关系计算并输出/显示极限值，安全限值确定是主要功能（DIRECT）。属计算/显示工具而非传感检测（sensor=NO），限值推导属阈值确定（decision=YES），本身不执行保护动作（response=NO）。主对象非机器人系统，NON_ROBOT。",
        "MEDIUM",
        5,
        TODAY,
    ],
    34: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "COLLISION_CONTACT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "RETREAT",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "在该外力检测部检测出的外力大于第一阈值的情况下, 指令上述机器人向减小外力的方向移动的退避动作……在规定时间内的上述外力的变动幅度小于第二阈值时停止上述躲避动作",
        "与材料包中 R023 同族（按外力躲避）：外力检测→超第一阈值→沿减小外力方向退避（RETREAT）；外力变动监视部在变动幅度小于第二阈值时停止躲避，使机器人仅在人有意施力时退避。完整机制链，harm=INDIRECT。",
        "HIGH",
        4,
        TODAY,
    ],
    35: [
        "COMPLETE",
        "PARTIAL",
        "DIRECT",
        "COLLISION_CONTACT",
        "BOTH",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "MIXED",
        "ABSTRACT",
        "detects unscheduled physical interventions…classifies interventions into intent categories such as accidental contact, trajectory correction, partial concession, demand for substitute performance, and emergency stop…intervention by underprivileged entities is limited to safety suspension",
        "First Claim 缺失，依据摘要：检测非计划人体物理干预（接触/抓握/阻挡，force profile+contact location+path occupancy，故 sensing=BOTH）→意图分类+权限分级→差异化移交控制权、低权限者限于安全悬停（MULTIPLE=STOP+降级/隔离）。安全门控与生产率（避免不必要全线停机）并重，PARTIAL+MIXED；明确物理接触，harm=DIRECT。受影响自由度隔离、其余并行维持，属遏制描述，propagation=ABSENT。",
        "MEDIUM",
        7,
        TODAY,
    ],
    36: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PHYSICAL_HRI",
        "UNCLEAR",
        "UNCLEAR",
        "UNCLEAR",
        "YES",
        "ISOLATE_OR_FALLBACK",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "用于人-机器人协作的生产站，包括……可在打开和关闭位置之间移动的门……通过其访问至一工作空间……关闭；-第一，在工作腔中排列机器人，其在与物体，特别是人接触时(22…（原文截断）",
        'MRK 生产站：周围保护装置+可开闭访问门（ISOLATE），工作腔内机器人"在与物体特别是人接触时…"——claim 原文在关键机制处截断，接触如何检测与判定无法确认（sensor/decision=UNCLEAR），但隔离防护明确（response=YES，barrier=YES）。主要依赖不完整文字，信心 LOW。',
        "LOW",
        6,
        TODAY,
    ],
    37: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PHYSICAL_HRI",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "RETREAT",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "一个或多个力控制或力控制的机器人轴线(I-VII)，具有作用在相应机器人轴线(I-VII)上的集成的负载，传感系统检测(11)，并且其中另外在加工工具的区域中(3)乘员保护装置(4 2)在与作业者身体接触的情况下，6)加工工具的偏转运动(3 2)或工具件允许的",
        "与材料包中 R009/R019 同族：力控轴集成负载检测（sensor=YES，力控含控制条件 decision=YES），人员保护装置在与作业者身体接触时允许加工工具偏转退让（RETREAT 型保护动作）。明确身体接触，harm=DIRECT。",
        "MEDIUM",
        5,
        TODAY,
    ],
}

# --- English glosses (NOT written to the workbook) ---
# Each row above contains two Chinese strings that are audit data written
# verbatim into 01_round1_blinded_review.xlsx; they are preserved unchanged so
# this script reproduces the recorded blinded review exactly:
#   - column W (quote): a verbatim quote from the original patent claim or
#     abstract, mostly Chinese-language patent text, kept as audit evidence;
#   - column X (reason): the reviewer's coding rationale, recorded in Chinese.
# Faithful English translations are given below, keyed by worksheet row, so
# that English-speaking reviewers can read the evidence and the rationale.
# Quotes that are already in English in the data are not repeated.
EN_GLOSS = {
    26: {
        "quote": "and when a human body is in the approach region, the output of the proximity sensor goes high, causing the robot controller to start moving the robot manipulator backward so as to avoid a collision.",
        "reason": "Industrial-robot safety belt: three infrared proximity sensors detect the human body by distance zone, the microcontroller judges according to the zone, and when a person enters the approach region the manipulator moves backward to avoid a collision (RETREAT); complete mechanism chain, explicitly avoiding collision (harm=DIRECT).",
    },
    27: {
        "quote": "when the sensor data indicates an external force exceeding a threshold force, stopping the motion of the at least one of the movable parts; and, in response to the measured speed exceeding a speed limit, stopping the motion of the at least one of the movable parts; Abstract: haptic warning and proximity sensing.",
        "reason": "Same family as R008 in the material package (housing element): force-threshold stop + overspeed stop (claim); the abstract specifies haptic warning and proximity sensing, hence sensing=BOTH and action=MULTIPLE (STOP+WARNING). Complete mechanism chain; the human-injury path is plausible but not explicitly stated, harm=INDIRECT.",
    },
    28: {
        "quote": "for measuring the distance (17) of one or more objects or body parts (12) ... and, on the basis of the combination of the distance information (17), the robot system (2) can be moved and guided through evaluation in the control system (9), in particular linearly or according to any desired characteristic curve.",
        "reason": "Non-contact guidance in an MRK setting: multiple distance sensors measure the distances of body parts, the control system evaluates the signals, and the robot's motion is guided. The abstract states the goal of 'secure and effective' collaboration, but the main function is non-contact guidance (interaction convenience); safety is an important but not the sole component, PARTIAL. There is no slowdown/stop protective-action wording, response=NO; the hazard-blocking effect is not explicitly stated, barrier=UNCLEAR.",
    },
    29: {
        "quote": "having elastic protrusions (12), and a robot sensor system for preventing accidents; Title/Abstract: A robot sensor for human-robot collision ... promote safety of a worker.",
        "reason": "Human-robot collision sensor: a contact-sensing structure of elastic conductors + grooves + elastic protrusions, explicitly 'preventing accidents' and promoting worker safety (harm=DIRECT). The claim only describes the sensor's mechanical structure, with no threshold/judgment or protective-response step, decision=NO and response=NO. The detection purpose is explicitly accident prevention, barrier=YES.",
    },
    30: {
        "quote": "a plurality of tactile sensors arranged on the robot body to detect contact ... determining a safety action based on the tactile data; and, in response to the detected contact, controlling the robot body to perform the safety action; Abstract: The safety action may comprise retracting the robot body away from a detected contact point.",
        "reason": "Same family as R004 in the material package (tactile sensing system for safe HRI): tactile sensing detects contact, a safety action is determined, and the safety action is executed; the abstract's example is retracting away from the detected contact point (RETREAT), with the action magnitude adjustable according to the contact force. Complete mechanism chain, explicitly aimed at safe HRI.",
    },
    31: {
        "quote": "generating a human safety zone (504) from sensing data and maintaining a robot safety zone (502) associated with the workspace of the robot arm; determining a degree of spatial overlap (508) between the human safety zone (504) and the robot safety zone (502); and adjusting an execution speed of a motion trajectory of the robot arm based on the determined spatial overlap.",
        "reason": "Imaging perceives hand position/proximity, human and robot safety zones are generated, and the execution speed is adjusted according to the degree of spatial overlap (SLOW); the safety mechanism is explicit. But an equally central part of the claim is a neural network that ranks trajectories by a 'collaboration productivity score' (a non-safety main function), hence PARTIAL+MIXED. The human-injury path is plausible but not explicitly stated, harm=INDIRECT.",
    },
    32: {
        "reason": "A fixing device for semiconductor grinding processing (rotating wheels + conveyor belt clamping the substrate); a purely mechanical fixture whose main subject is not a robot system (NON_ROBOT), with no safety mechanism at all.",
    },
    33: {
        "quote": "for determining safety limit values for human-robot collaboration with the system, and configured to output ... limit values (V111, V124, V224) on the basis of ... a mechanically fixed relationship between the first and second parameters (V, M, A, K) and predetermined values.",
        "reason": "A portable handheld device for determining safety limit values of an HRC system: it computes and outputs/displays limit values from fixed relationships between parameters; safety-limit determination is the main function (DIRECT). It is a computation/display tool rather than sensed detection (sensor=NO); deriving the limits is threshold determination (decision=YES); it performs no protective action itself (response=NO). The main subject is not a robot system, NON_ROBOT.",
    },
    34: {
        "quote": "in the case where the external force detected by the external-force detection part is greater than a first threshold, instructing a retreat motion that moves the robot in the direction of decreasing the external force ... stopping the avoidance motion when the variation amplitude of the external force within a prescribed time is smaller than a second threshold.",
        "reason": "Same family as R023 in the material package (avoidance by external force): external-force detection, exceeding the first threshold, then retreat in the direction that reduces the external force (RETREAT); an external-force-variation monitoring part stops the avoidance when the variation amplitude falls below the second threshold, so the robot retreats only when the person intentionally applies force. Complete mechanism chain, harm=INDIRECT.",
    },
    35: {
        "reason": "The first claim is missing, so the coding rests on the abstract: unscheduled physical interventions by a person are detected (contact/grasping/blocking, via force profile + contact location + path occupancy, hence sensing=BOTH), intents are classified and privileges graded, and control authority is handed over differentially, with underprivileged entities limited to safety suspension (MULTIPLE=STOP + downgrade/isolation). Safety gating and productivity (avoiding unnecessary whole-line stoppages) are weighted equally, PARTIAL+MIXED; physical contact is explicit, harm=DIRECT. Affected degrees of freedom are isolated while the rest are maintained in parallel, a containment description, propagation=ABSENT.",
    },
    36: {
        "quote": "a production station for human-robot collaboration, comprising ... a door movable between an open and a closed position ... through which access to a working space is gained ... closed; first, arranging in the working chamber a robot which, upon contact with an object, in particular a person (22 ... (original text truncated).",
        "reason": "MRK production station: surrounding protective device + an openable/closable access door (ISOLATE); the robot in the working chamber acts 'upon contact with an object, in particular a person ...', but the original claim text is truncated exactly at the key mechanism, so how contact is detected and judged cannot be confirmed (sensor/decision=UNCLEAR); the isolation-type protection is explicit (response=YES, barrier=YES). The coding relies mainly on incomplete text, confidence LOW.",
    },
    37: {
        "quote": "one or more force-controlled robot axes (I-VII) with an integrated sensing system (11) detecting the load acting on the respective robot axis, and wherein additionally, in the region of the machining tool (3), a personal-protection device (4) which, in the event of contact with the operator's body, permits a deflecting motion of the machining tool (3) or of the tool piece.",
        "reason": "Same family as R009/R019 in the material package: force-controlled axes with integrated load detection (sensor=YES; force control implies a control condition, decision=YES); the personnel-protection device permits the machining tool to deflect and yield upon contact with the operator's body (a RETREAT-type protective action). Bodily contact is explicit, harm=DIRECT.",
    },
}

wb = openpyxl.load_workbook(PATH)
ws = wb["01_REVIEW"]
for r, vals in ROWS.items():
    for i, v in enumerate(vals):
        ws.cell(row=r, column=9 + i, value=v)
try:
    wb.save(PATH)
except PermissionError:
    print("LOCKED: file still open in Excel, nothing saved")
    sys.exit(2)
print("SAVED rows 26-37, date =", TODAY)
