"""Write batch 4 (rows 38-49, R037-R048) reviewer fields. Only touches columns I-AA."""

import datetime
import sys

import openpyxl

PATH = "01_round1_blinded_review.xlsx"
TODAY = datetime.date.today().isoformat()

ROWS = {
    38: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "NONE",
        "NONE",
        "NO",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "基于所述输入信号产生多个控制信号，以控制所述移动基座和至少一个其它可移动元件的移动，从而通过优化所述可移动元件和所述移动基座的移动和位置的预定标量函数来实现所需的移动",
        "移动基座+机械臂的协同运动优化控制（标量函数优化），纯运动控制方法，无安全机制、无接触/接近语境。优化求解控制信号属控制条件判断，decision=YES。",
        "HIGH",
        4,
        TODAY,
    ],
    39: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "NONE",
        "NONE",
        "NO",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "执行被配置为对与资源和任务相关联的信息进行编码的图网络；以及执行递归解码器……在考虑由所述图网络建立的一个或多个时空约束的同时确定调度……所述计划表用于控制或监测一个或多个机器人系统",
        "基于异质图网络+递归解码器的人-机器人团队任务调度学习，属调度/AI（手册列 OFF_TOPIC 的调度类），无安全机制、无物理感知环节。调度确定属判断，decision=YES。",
        "HIGH",
        4,
        TODAY,
    ],
    40: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "COLLISION_CONTACT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "the contact with the robot when the person stops the action of the robot, and a speed limiting part for limiting the action speed……when the variable is in the range, the action speed of the structure component control is less than a predetermined limit speed",
        '人接触机器人时停止（STOP）+ 按驱动轴位置变量处于"人被机器人/工具夹住范围"时限速至预定极限以下（SLOW），MULTIPLE。明确人接触与夹住状态，harm=DIRECT。翻译质量差但机制链可辨，信心 MEDIUM。',
        "MEDIUM",
        6,
        TODAY,
    ],
    41: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "UNCLEAR",
        "UNCLEAR",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "分配至少一个保护区，其由与机器人相互作用的检测元件检测……其被设计成根据机器人活动和/或机器人工作位置在其范围和功能方面变化和/或可变",
        "冶金/轧机自动化：机器人分配保护区并由检测元件检测、保护区随机器人活动/位置可变，HRI 操作模式适配自动化程度与人机定位，面向高温/危险区域（abstract: hot and/or danger zone, safer）。检测与适配明确（sensor/decision=YES），但保护动作因译文残缺无法确认（response/action=UNCLEAR）。",
        "LOW",
        6,
        TODAY,
    ],
    42: [
        "COMPLETE",
        "PARTIAL",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "UNCLEAR",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "至少一个对准协同工作空间的成像装置，以单独跟踪协同工作空间内人体构件的位置；其中所述控制器被配置为基于执行所述至少一个人工执行的操作的身体构件的单独跟踪位置来引导执行所述至少一个机器人操作的所述至少一个机器人的运动",
        "与材料包中 R013 claim 文本相同（同族，标题为 Safe assembly cell）：成像跟踪人体构件位置→引导机器人运动，接近监测型 HRI 机制但无安全用语，PARTIAL；无保护动作文字 response=NO，barrier=UNCLEAR。",
        "MEDIUM",
        4,
        TODAY,
    ],
    43: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PHYSICAL_HRI",
        "BOTH",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "通过上述接近传感器检测出人侵入上述第一领域内……使上述人协调型机器人以及上述移动装置各部分对地板的动作速度在人能够协调作业的规定协调动作速度以下……当检测到该系统时，该系统控制移动式人协作机器人停止或避免人与人之间的接触",
        "移动式人协调机器人双区防护：第一领域接近传感→限速至协调动作速度以下（SLOW）；第二领域人感传感器检测接触→停止或避免接触（STOP）。sensing=BOTH，action=MULTIPLE，明确人接触避免，harm=DIRECT，完整机制链。",
        "HIGH",
        5,
        TODAY,
    ],
    44: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "NONE",
        "NONE",
        "NO",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "执行被配置为对与资源和任务相关联的信息进行编码的图网络；以及执行递归解码器……在考虑由所述图网络建立的一个或多个时空约束的同时确定调度",
        "与材料包中 R038 claim 文本相同（同族）：图网络+递归解码器的任务调度学习，OFF_TOPIC，无安全机制。调度确定属判断，decision=YES。",
        "HIGH",
        3,
        TODAY,
    ],
    45: [
        "COMPLETE",
        "PARTIAL",
        "DIRECT",
        "COLLISION_CONTACT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "MULTIPLE",
        "Abstract: to prevent accidents in task by informing excessive contact force to an operator through a monitoring device and controlling the contact force by a robot controller",
        "HRC 零件装配方法：claim 译文混乱（示教位置存储+peg-in-hole 修正），摘要明确通过监测装置向操作者告知过大接触力（WARNING）并由控制器控制接触力（LIMIT_FORCE）以防作业事故，MULTIPLE。主功能为装配、安全为重要组成，PARTIAL；明确事故防止与接触力，harm=DIRECT。",
        "MEDIUM",
        6,
        TODAY,
    ],
    46: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "YES",
        "OTHER",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "reading the maximum range diameter of history execution instruction set, and generating operation warning range; …comparing the working range with the operation warning range, obtaining the execution value A, the execution value A comprises 1 or 0; the execution module is used for judging the work based on the execution value A",
        '安全交互人-机器人协作机器人：识别机器人空间位置、按历史指令集最大包络生成"操作警戒范围"→将指令工作范围与警戒范围比较得执行值 A(0/1)→执行模块按 A 判定是否作业（指令门控，记 OTHER）。安全范围门控为主要功能（DIRECT），人体伤害路径合理但未明言，harm=INDIRECT。',
        "MEDIUM",
        5,
        TODAY,
    ],
    47: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "NONE",
        "NO",
        "NO",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "至少一个吊舱框架，所述至少一个吊舱框架被配置成容纳一个或多个双臂机器人……所述吊舱框架是模块化的并且可重新配置以支持用于在工作空间内容纳不同数量的机器人的多个空间配置",
        "模块化机器人吊舱系统：框架+线轨+旋转平台容纳双臂机器人、可重构布局，纯设备布置/物流，无安全机制。",
        "HIGH",
        3,
        TODAY,
    ],
    48: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "FORCE_TORQUE",
        "YES",
        "NO",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "一种多轴，可编程的机器人支撑装置(26)和可编程机器人的多轴和触觉装置(27)，具有向机器人手臂(37)的支撑机器人(26)安装",
        '工件搬运装置：搬运机器人臂上安装触觉工业机器人，面向工件搬运，无安全用语（NOT_SAFETY）。"触觉"表明力/接触型感知存在（sensing=FORCE_TORQUE, sensor=YES），无判断与保护环节。',
        "MEDIUM",
        4,
        TODAY,
    ],
    49: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "NONE",
        "NO",
        "NO",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "工件夹持器(2)框架(8)安装有可移动和可锁定的引导件(10)……通过控制和锁定装置的操作来扩大其工作区域",
        "加工过程控制：可调可锁定工件夹持器+工业机器人操作以扩大工作区域，面向工件装夹，无安全机制。",
        "HIGH",
        3,
        TODAY,
    ],
}

wb = openpyxl.load_workbook(PATH)
ws = wb["01_REVIEW"]
for r, vals in ROWS.items():
    for i, v in enumerate(vals):
        ws.cell(row=r, column=9 + i, value=v)
try:
    wb.save(PATH)
except PermissionError:
    print("LOCKED: file still open in Excel, nothing saved")
    sys.exit(2)
print("SAVED rows 38-49, date =", TODAY)
