"""Write batch 1 (rows 2-13, R001-R012) reviewer fields into 01_round1_blinded_review.xlsx.
Only touches pale-yellow columns I-AA. Never touches A-H."""

import datetime
import sys

import openpyxl

PATH = "01_round1_blinded_review.xlsx"
TODAY = datetime.date.today().isoformat()

# columns: I status, J safety, K harm, L contact, M sensing, N sensor, O decision, P response,
# Q action, R humanoid, S barrier, T propagation, U scope, V ev_loc, W quote, X reason, Y conf, Z minutes, AA date
ROWS = {
    2: [
        "COMPLETE",
        "PARTIAL",
        "INDIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "YES",
        "SLOW",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "MIXED",
        "FIRST_CLAIM",
        "所述可变运动参数的限制以这样的方式预先定义，即运动参数的每个可变变量确保安全的人-机器人协作；在检测到所述人类协作者的异常状态的情况下，至少一个运动参数自动地朝向其下限改变",
        '主功能是交互式在线调整运动参数（编程便利性），但参数限值明确以"确保安全的人-机器人协作"预定义，且检测协作人异常状态自动下调参数，安全是重要组成而非唯一主功能，故 PARTIAL+MIXED。检测人位置→异常判断→降速下限，三环节文字齐备。',
        "MEDIUM",
        6,
        TODAY,
    ],
    3: [
        "COMPLETE",
        "PARTIAL",
        "INDIRECT",
        "OBJECT_ENVIRONMENT",
        "NONE",
        "NO",
        "NO",
        "YES",
        "LIMIT_FORCE",
        "NON_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "能够提供对基座(16)的定位驱动(64)施加定位力的钳口，允许的极限力不超过",
        "权利要求主体是夹持/夹紧单元（末端执行器）而非机器人系统，按手册判 NON_ROBOT。区别特征为定位驱动力受限（极限力不超过），属限力保护设计，面向 HRC 使用场景有合理防夹伤下游路径但文本未明言人体伤害；无传感检测与阈值判断文字。限力安全特征是发明点，故 IN_SCOPE。",
        "MEDIUM",
        5,
        TODAY,
    ],
    4: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PHYSICAL_HRI",
        "NONE",
        "NO",
        "NO",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "MULTIPLE",
        "工作站(1)……提供多个不同区域的人-机器人协作(MRK)……具有不同水平的工业机器人(4)对操作者的危险程度；Abstract: Contact between the worker (5) and the industrial robot (4) is possible.",
        "按机器人对操作者的危险程度将工作站划分为不同风险等级区域，危险分区本身是主要技术内容（DIRECT）；摘要明确工人与机器人工作区重叠、接触可能，人体伤害联系明确。按危险分区限制/管理风险属组织性危险限制措施，barrier=YES。文本无传感、判断与保护响应环节。",
        "MEDIUM",
        5,
        TODAY,
    ],
    5: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "COLLISION_CONTACT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "RETREAT",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "MULTIPLE",
        "多个触觉传感器，其设置在所述机器人主体上以检测接触……基于所述触觉数据确定安全动作；以及响应于检测到的接触，控制机器人本体执行安全动作；Abstract: The safety action may comprise retracting the robot body away from a detected contact point.",
        '模块化机器人皮肤：触觉传感检测接触→基于触觉数据确定安全动作→执行安全动作（摘要示例为远离接触点回缩），完整机制链三环节均为 YES。文本明确以"安全的人-机器人交互"为目的，接触检测直接关联人体碰撞防护。',
        "HIGH",
        4,
        TODAY,
    ],
    6: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "COLLISION_CONTACT",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "当检测到的外力在第一阈值以上时，所述控制装置停止所述机器人的动作，当检测到的外力在超过第一阈值的第二阈值以上时，进行警告",
        "外力传感→双阈值比较→停止+警告（MULTIPLE=STOP+WARNING），完整机制链。声称目的是防止机器人过载（含不熟练用户场景），人体伤害为合理下游路径但未明言，故 harm=INDIRECT。",
        "HIGH",
        4,
        TODAY,
    ],
    7: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "NONE",
        "NO",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "PLAUSIBLE_ONLY",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "确定单元，其确定关于所述对象的作业类型；以及控制单元，其控制与由所述确定单元确定的所述作业类型相对应的所述工具的附接操作",
        "内容为按作业类型自动换工具的任务控制，无安全机制（NOT_SAFETY/OFF_TOPIC）。作业类型判定属分类判断故 decision=YES。确定单元输出→控制单元条件是正常控制流，按校准口径不判明确跨子系统传播，记 PLAUSIBLE_ONLY。",
        "HIGH",
        4,
        TODAY,
    ],
    8: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "OBJECT_ENVIRONMENT",
        "NONE",
        "NO",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "The controller is configured to control the vertical staggered arrangement of the load-carrying mechanisms (2) of the two robots located in the two adjacent cells (6) when the preset conditions are met",
        '仓储机器人调度：按预设条件控制相邻格子两机器人载货机构竖向错位，属物流/调度，无安全机制（摘要中"human-robot"为机器人调度的误译）。"预设条件满足"属控制条件判断故 decision=YES，无传感检测与保护响应文字。',
        "HIGH",
        4,
        TODAY,
    ],
    9: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "COLLISION_CONTACT",
        "BOTH",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "MULTIPLE",
        "当所述传感器数据指示超过阈值力的力时，停止所述可移动部件中的所述至少一个的运动，以及响应于所测量的速度超过速度限制，停止所述可移动部件中的所述至少一个的运动；Abstract: haptic warning and proximity sensing",
        "力阈值停止+超速停止（claim），摘要另明确触觉振动告警与接近感知，故 sensing=BOTH、action=MULTIPLE(STOP+WARNING)。完整机制链，面向 HRC 安全防护；人体伤害路径合理但文本未明言伤害，harm=INDIRECT。",
        "HIGH",
        5,
        TODAY,
    ],
    10: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PHYSICAL_HRI",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "OTHER",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "所述机器人轴具有集成的、在相应的机器人轴(I-VII)上具有作用负载的检测传感器系统(11)，并且其中，在所述加工工具(3)的区域中附加地布置有个人保护装置(4)",
        "HRC 工业机器人：力控轴集成负载检测传感（sensor=YES，力控含控制条件 decision=YES），加工工具附近附加人员保护装置——人身保护明确（harm=DIRECT）。保护装置具体动作类型文本未说明，记 OTHER。",
        "MEDIUM",
        5,
        TODAY,
    ],
    11: [
        "COMPLETE",
        "DIRECT",
        "INDIRECT",
        "PHYSICAL_HRI",
        "FORCE_TORQUE",
        "YES",
        "YES",
        "YES",
        "MULTIPLE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "FIRST_CLAIM",
        "the security to make the robot to for reducing the external force direction moves or causes the robot to stop to ensure the action instruction",
        "人机共享工作空间：第一力检测部测外力→与阈值比较（手动操作时扣除第二检测部测得的操作力）→使机器人沿减小外力方向移动或停止（MULTIPLE=RETREAT+STOP）。安全保障运行为主要功能；外力涉及人但未明言伤害，harm=INDIRECT。",
        "HIGH",
        5,
        TODAY,
    ],
    12: [
        "COMPLETE",
        "NOT_SAFETY",
        "NONE",
        "NONE",
        "OTHER",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "NO",
        "ABSENT",
        "OFF_TOPIC",
        "FIRST_CLAIM",
        "确定所述任务步骤列表中的每个任务步骤对应于由所述传感器捕获的所述场景中的人类的行为的概率；基于所述概率确定预测的下一意图步骤",
        "意图跟踪：视觉捕获场景、检测对象、预测人类下一意图步骤并执行对应操作。手册明确将意图跟踪列为 OFF_TOPIC；无安全用语（NOT_SAFETY）。检测人的行为属 sensor=YES（视觉故 sensing=OTHER），意图/概率判断 decision=YES，无保护响应。",
        "HIGH",
        4,
        TODAY,
    ],
    13: [
        "COMPLETE",
        "DIRECT",
        "DIRECT",
        "PROXIMITY_SEPARATION",
        "PROXIMITY",
        "YES",
        "YES",
        "NO",
        "NONE",
        "GENERAL_ROBOT",
        "YES",
        "ABSENT",
        "IN_SCOPE",
        "MULTIPLE",
        "使用自动化的评估模块确定用于所述轨迹(path)的允许的过程速度(v_zul)(38)；-将实际处理速度(v_POI，v_TCP)与所述允许处理速度(v_zul)进行比较；Abstract: optionally body zones or body parts at risk of collision are specified",
        "HRC 过程监控：记录布局与协作区域、检测运动路径→评估模块确定允许过程速度→与实际速度比较。摘要明确指定有碰撞风险的身体部位（harm=DIRECT）。机制基于空间布局/区域的速度-分离监控（PROXIMITY_SEPARATION）。权利要求步骤止于速度比较，无保护动作文字，response=NO。",
        "MEDIUM",
        6,
        TODAY,
    ],
}

# --- English glosses (NOT written to the workbook) ---
# Each row above contains two Chinese strings that are audit data written
# verbatim into 01_round1_blinded_review.xlsx; they are preserved unchanged so
# this script reproduces the recorded blinded review exactly:
#   - column W (quote): a verbatim quote from the original patent claim or
#     abstract, mostly Chinese-language patent text, kept as audit evidence;
#   - column X (reason): the reviewer's coding rationale, recorded in Chinese.
# Faithful English translations are given below, keyed by worksheet row, so
# that English-speaking reviewers can read the evidence and the rationale.
# Quotes that are already in English in the data are not repeated.
EN_GLOSS = {
    2: {
        "quote": "The limits of the variable motion parameters are predefined in such a way that every variable of the motion parameters ensures safe human-robot collaboration; if an abnormal state of the human collaborator is detected, at least one motion parameter is automatically changed toward its lower limit.",
        "reason": "The main function is interactive online adjustment of motion parameters (programming convenience), but the parameter limits are explicitly predefined to 'ensure safe human-robot collaboration', and detecting an abnormal state of the collaborating human automatically lowers the parameter toward its limit; safety is an important component rather than the sole main function, hence PARTIAL+MIXED. Detecting the human's position, judging the abnormality, and reducing speed to the lower limit: all three steps of the chain are present in the text.",
    },
    3: {
        "quote": "jaws capable of applying a positioning force to the positioning drive (64) of the base (16), the permissible limit force not exceeding ...",
        "reason": "The claimed subject is a gripping/clamping unit (end effector), not a robot system, so NON_ROBOT per the codebook. The distinguishing feature is the limited positioning drive force (limit force not exceeded), a force-limiting protective design with a plausible downstream anti-pinch path in HRC use, though the text does not explicitly mention human injury; there is no sensing/detection or threshold-judgment wording. The force-limiting safety feature is the point of invention, hence IN_SCOPE.",
    },
    4: {
        "quote": "Workstation (1) ... providing several zones for human-robot collaboration (MRK) with different levels of hazard posed by the industrial robot (4) to the operator; Abstract: Contact between the worker (5) and the industrial robot (4) is possible.",
        "reason": "The workstation is divided into zones of different risk levels according to how hazardous the robot is to the operator; the hazard zoning itself is the main technical content (DIRECT). The abstract explicitly states that the worker's and robot's work areas overlap and that contact is possible, so the link to human injury is explicit. Managing risk through hazard zoning is an organizational hazard-limitation measure, barrier=YES. The text has no sensing, judgment, or protective-response step.",
    },
    5: {
        "quote": "a plurality of tactile sensors arranged on the robot body to detect contact ... determining a safety action based on the tactile data; and, in response to the detected contact, controlling the robot body to perform the safety action; Abstract: The safety action may comprise retracting the robot body away from a detected contact point.",
        "reason": "Modular robot skin: tactile sensing detects contact, a safety action is determined from the tactile data, and the safety action is executed (the abstract's example is retracting away from the detected contact point); all three steps of the complete mechanism chain are YES. The text explicitly states 'safe human-robot interaction' as the purpose, and contact detection is directly tied to human collision protection.",
    },
    6: {
        "quote": "when the detected external force is at or above a first threshold, the control device stops the motion of the robot, and when the detected external force is at or above a second threshold that exceeds the first threshold, a warning is issued.",
        "reason": "External-force sensing, two-threshold comparison, then stop + warning (MULTIPLE=STOP+WARNING): a complete mechanism chain. The stated purpose is to prevent robot overload (including use by unskilled operators); human injury is a plausible downstream path but is not explicitly stated, hence harm=INDIRECT.",
    },
    7: {
        "quote": "a determination unit that determines a work type relating to the object; and a control unit that controls the attachment operation of the tool corresponding to the work type determined by the determination unit.",
        "reason": "The content is task control that automatically changes tools according to the work type, with no safety mechanism (NOT_SAFETY/OFF_TOPIC). Work-type determination is classification judgment, hence decision=YES. Determination-unit output feeding the control unit is a normal control flow; per the calibration convention it is not coded as explicit cross-subsystem propagation, so PLAUSIBLE_ONLY.",
    },
    8: {
        "reason": "Warehouse robot scheduling: when preset conditions are met, the load-carrying mechanisms of two robots in adjacent cells are controlled into a vertically staggered arrangement; this is logistics/scheduling with no safety mechanism (the 'human-robot' wording in the abstract is a mistranslation of robot scheduling). 'Preset conditions met' is a control-condition judgment, hence decision=YES; there is no sensing-detection or protective-response wording.",
    },
    9: {
        "quote": "when the sensor data indicates a force exceeding a threshold force, stopping the motion of the at least one of the movable parts; and, in response to the measured speed exceeding a speed limit, stopping the motion of the at least one of the movable parts; Abstract: haptic warning and proximity sensing.",
        "reason": "Force-threshold stop + overspeed stop (claim); the abstract additionally specifies haptic warning and proximity sensing, hence sensing=BOTH and action=MULTIPLE (STOP+WARNING). Complete mechanism chain aimed at HRC safety protection; the human-injury path is plausible but the text does not explicitly mention injury, harm=INDIRECT.",
    },
    10: {
        "quote": "the robot axes have an integrated detection sensor system (11) for the load acting on the respective robot axis (I-VII), and a personal-protection device (4) is additionally arranged in the region of the machining tool (3).",
        "reason": "HRC industrial robot: force-controlled axes with integrated load-detection sensing (sensor=YES; force control implies a control condition, decision=YES), plus a personnel-protection device near the machining tool, so personnel protection is explicit (harm=DIRECT). The protection device's specific action type is not described in the text, coded OTHER.",
    },
    11: {
        "reason": "Shared human-robot workspace: a first force-detection part measures the external force, it is compared with a threshold (during manual operation the operating force measured by a second detection part is subtracted), and the robot is moved in the direction that reduces the external force or is stopped (MULTIPLE=RETREAT+STOP). Safety-assurance operation is the main function; the external force involves a human but injury is not explicitly stated, harm=INDIRECT.",
    },
    12: {
        "quote": "determining a probability that each task step in the task-step list corresponds to an action of the human in the scene captured by the sensor; and determining a predicted next intent step based on the probabilities.",
        "reason": "Intent tracking: vision captures the scene and detects objects, predicts the human's next intent step, and executes the corresponding operation. The codebook explicitly lists intent tracking as OFF_TOPIC; no safety language (NOT_SAFETY). Detecting the person's action gives sensor=YES (vision, hence sensing=OTHER); the intent/probability judgment gives decision=YES; no protective response.",
    },
    13: {
        "quote": "determining, with an automated evaluation module, a permissible process speed (v_zul) (38) for the path; comparing the actual process speed (v_POI, v_TCP) with the permissible process speed (v_zul); Abstract: optionally body zones or body parts at risk of collision are specified.",
        "reason": "HRC process monitoring: the layout and collaboration zones are recorded and the motion path is detected, the evaluation module determines the permissible process speed, and it is compared with the actual speed. The abstract explicitly specifies body parts at risk of collision (harm=DIRECT). The mechanism is speed-and-separation monitoring based on the spatial layout/zones (PROXIMITY_SEPARATION). The claim steps stop at the speed comparison with no protective-action wording, response=NO.",
    },
}

wb = openpyxl.load_workbook(PATH)
ws = wb["01_REVIEW"]
for r, vals in ROWS.items():
    for i, v in enumerate(vals):
        ws.cell(row=r, column=9 + i, value=v)
try:
    wb.save(PATH)
except PermissionError:
    print("LOCKED: file still open in Excel, nothing saved")
    sys.exit(2)
print("SAVED rows 2-13, date =", TODAY)
